import type { Listing } from './listingSchema'

export const sampleListings: Listing[] = [
  {
    id: 'sample-terrace-studio',
    title: 'Bright terrace studio near old town',
    location: 'Bucharest, Romania',
    neighborhood: 'Old Town',
    url: 'https://example.com/listings/terrace-studio',
    priceNightly: 92,
    cleaningFee: 28,
    bedrooms: 1,
    bathrooms: 1,
    guests: 2,
    rating: 4.82,
    reviewCount: 184,
    latitude: 44.432,
    longitude: 26.103,
    amenities: ['terrace', 'self check-in', 'air conditioning', 'fast Wi-Fi'],
    minNights: 2,
    occupancyHint: 0.81,
    source: 'sample',
  },
  {
    id: 'sample-family-flat',
    title: 'Quiet family flat with parking',
    location: 'Bucharest, Romania',
    neighborhood: 'Cotroceni',
    url: 'https://example.com/listings/family-flat',
    priceNightly: 138,
    cleaningFee: 40,
    bedrooms: 2,
    bathrooms: 1.5,
    guests: 5,
    rating: 4.76,
    reviewCount: 96,
    latitude: 44.43,
    longitude: 26.071,
    amenities: ['parking', 'washer', 'crib', 'kitchen'],
    minNights: 3,
    occupancyHint: 0.68,
    source: 'sample',
  },
  {
    id: 'sample-design-loft',
    title: 'Design loft with skyline view',
    location: 'Bucharest, Romania',
    neighborhood: 'Unirii',
    url: 'https://example.com/listings/design-loft',
    priceNightly: 176,
    cleaningFee: 50,
    bedrooms: 2,
    bathrooms: 2,
    guests: 4,
    rating: 4.91,
    reviewCount: 211,
    latitude: 44.425,
    longitude: 26.11,
    amenities: ['view', 'elevator', 'espresso machine', 'workspace', 'fast Wi-Fi'],
    minNights: 2,
    occupancyHint: 0.77,
    source: 'sample',
  },
  {
    id: 'sample-budget-room',
    title: 'Simple room by the metro',
    location: 'Bucharest, Romania',
    neighborhood: 'Tineretului',
    url: 'https://example.com/listings/budget-room',
    priceNightly: 54,
    cleaningFee: 16,
    bedrooms: 1,
    bathrooms: 1,
    guests: 2,
    rating: 4.52,
    reviewCount: 73,
    latitude: 44.413,
    longitude: 26.105,
    amenities: ['metro nearby', 'washer', 'shared kitchen'],
    minNights: 1,
    occupancyHint: 0.85,
    source: 'sample',
  },
  {
    id: 'sample-premium-penthouse',
    title: 'Premium penthouse with private sauna',
    location: 'Bucharest, Romania',
    neighborhood: 'Primaverii',
    url: 'https://example.com/listings/premium-penthouse',
    priceNightly: 312,
    cleaningFee: 75,
    bedrooms: 3,
    bathrooms: 2.5,
    guests: 6,
    rating: 4.88,
    reviewCount: 58,
    latitude: 44.468,
    longitude: 26.09,
    amenities: ['sauna', 'parking', 'balcony', 'king bed', 'concierge'],
    minNights: 3,
    occupancyHint: 0.59,
    source: 'sample',
  },
  {
    id: 'sample-workation-apartment',
    title: 'Workation apartment with two desks',
    location: 'Bucharest, Romania',
    neighborhood: 'Floreasca',
    url: 'https://example.com/listings/workation-apartment',
    priceNightly: 149,
    cleaningFee: 38,
    bedrooms: 2,
    bathrooms: 1,
    guests: 4,
    rating: 4.69,
    reviewCount: 137,
    latitude: 44.46,
    longitude: 26.1,
    amenities: ['two desks', 'monitor', 'fast Wi-Fi', 'coffee', 'balcony'],
    minNights: 4,
    occupancyHint: 0.72,
    source: 'sample',
  },
]
